###############################################################
# Program:
#     Checkpoint 04b, Classes
#     Brother McCracken, CS165
# Author:
#     Amy Chambers
# Summary:
#     Summaries are not necessary for checkpoint assignments.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : date.h date.cpp check04b.cpp
	g++ date.cpp check04b.cpp

